inherit_from: .rubocop_todo.yml

AllCops:
  RunRailsCops: true
  Exclude:
    - lib/generators/*/templates/**/*

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise
  Exclude:
    - test/**/*

Style/SingleLineMethods:
  Exclude:
    - test/**/*

Lint/UnusedMethodArgument:
  Enabled: false
