require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-erb
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'gemfiles/Gemfile*.lock'
    - 'bin/*'
    - 'lib/generators/**/templates/**/*'
    - 'vendor/bundle/**/*'
    - 'test/mock_app/**/*'

# we allow long lines yet, because there are many to fix, and it would enforce to create long lines
Style/IfUnlessModifier:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/ClassLength:
  Max: 500
  CountComments: false

Layout/LineLength:
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - test/**/*
    # TODO: cleanup the next files
    - lib/active_scaffold/helpers/*
    - lib/active_scaffold/extensions/*
    - lib/active_scaffold/bridges/**/*
    - lib/active_scaffold/config/*
    - lib/active_scaffold/data_structures/*
    - lib/active_scaffold/actions/core.rb
    - lib/active_scaffold/finder.rb
    - lib/active_scaffold/constraints.rb
    - lib/active_scaffold/active_record_permissions.rb
    - lib/active_scaffold/core.rb
    - lib/active_scaffold/tableless.rb

Metrics/ModuleLength:
  Max: 700
  CountComments: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Naming/FileName:
  Exclude:
    - Gemfile
    - Rakefile
    - test/mock_app/Rakefile
    - vendor/assets/stylesheets/jquery-ui-theme.css.erb

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional

Naming/VariableNumber:
  CheckSymbols: false

Performance/RedundantMerge:
  MaxKeyValuePairs: 1

Rails:
  Enabled: true

Rails/ApplicationRecord:
  Exclude:
    - 'test/**/*'

Rails/DynamicFindBy:
  Whitelist:
    - find_by_name
    - find_by_names

Rails/RakeEnvironment:
  Exclude:
    - lib/tasks/brakeman.rake

Rails/ActionControllerTestCase:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Exclude:
    - 'test/**/*'
