inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'gemfiles/Gemfile*.lock'
    - 'bin/*'
    - 'lib/generators/**/templates/**/*'
    - 'vendor/bundle/**/*'

# we allow long lines yet, because there are many to fix, and it would enforce to create long lines
Style/IfUnlessModifier:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/ClassLength:
  Max: 500
  CountComments: false

Metrics/LineLength:
  Exclude:
    - 'test/**/*'

Metrics/ModuleLength:
  Max: 650
  CountComments: false

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'test/mock_app/Rakefile'

Performance/RedundantMerge:
  MaxKeyValuePairs: 1

Rails:
  Enabled: true

Rails/ApplicationRecord:
  Exclude:
    - 'test/**/*'

Rails/DynamicFindBy:
  Whitelist:
    - find_by_name
    - find_by_names

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/FormatString:
  EnforcedStyle: percent

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Enabled: false # FIXME

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Exclude:
    - 'test/**/*'
