# Site settings
title: Active Scaffold
email: sergio@activescaffold.eu
description: >- # this means to ignore newlines until next key
  ActiveScaffold helps developers rapidly build and manage web applications
  with flexible scaffolding, automation, and developer-friendly tools. 
baseurl: "" # the subpath of your site, e.g., /blog (leave empty for username.github.io)
url: "https://activescaffold.eu" # the base hostname & protocol for your site
github_username: activescaffold
sass:
  sass_dir: _sass
kramdown:
  input: GFM
  extensions: [attr_list]

collections:
  posts:
    output: true
  pages:
    output: true
    permalink: /:path/
  echo_kb_faqs:
    output: true
    permalink: /faq/:title/
  epkb_post_type_1s:
    output: true
    permalink: /kb/:title/

# Default settings for collections
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
  - scope:
      path: ""
      type: "echo_kb_faqs"
    values:
      layout: post
  - scope:
      path: ""
      type: "epkb_post_type_1s"
    values:
      layout: post
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

# Build settings
theme: minima # or another GitHub Pages supported theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2

# WordPress import specific
permalink: /:year/:month/:day/:title/

############################################################
# jekyll-paginate-v2
############################################################
pagination:
  enabled: true
  per_page: 3
  permalink: "/page:num/"
  sort_field: "date"
  sort_reverse: true

autopages:
  enabled: true
  categories:
    enabled: true
    layouts:
      - "category_index.html"
    title: ":cat"
    permalink: "/category/:cat"
  tags:
    enabled: false
  collections:
    enabled: false

exclude:
  - Gemfile
  - Gemfile.lock
  - CLAUDE.md
  - vendor
  - .bundle
  - .sass-cache
  - .github
