# frozen_string_literal: true

module ActiveScaffold
  module Assets
    class CssDepsGenerator
      class << self
        def generate!
          generator = new
          generator.generate!
        end
      end

      def initialize
        @css_path = Rails.root.join('app/assets/stylesheets/active_scaffold/deps.scss')
      end

      def generate!
        Rails.logger.info 'ActiveScaffold: Generating deps.css...'
        perform_generation
      end

      private
      def perform_generation
        content = ActiveScaffold::Assets.active_scaffold_stylesheets(:deps).map do |sheet|
          "@use '#{sheet}';\n"
        end
        content.unshift("/* File autogenerated by ActiveScaffold, don't modify it */\n\n")

        # Ensure directory exists
        FileUtils.mkdir_p(File.dirname(@css_path))

        # Write the processed file
        File.write(@css_path, content.join)

        Rails.logger.info "✅ ActiveScaffold: deps.css generated at #{@css_path}"
      rescue StandardError => e
        Rails.logger.error "ActiveScaffold: Failed to generate deps.css: #{e.message}"
      end
    end
  end
end
